#!/usr/bin/env python3
"""Turn scripts/output/pois_raw.json into the shipped data/pois-*.js files.

Pipeline: fetch_pois.py -> pois_raw.json -> [dedupe] -> data/pois-*.js
This is the last step, and the only one that writes into data/.

WIRE FORMAT

Each region file is an array of positional arrays rather than objects:

  const P_SCOTLAND=[["Edinburgh Castle",3,55.94859,-3.19776,142], ...];
                     name             cat  lat      lng      score

Measured on the real dataset, positional arrays are 321KB gzipped against
413KB for objects — and since the UI inflates them to
{name,category,lat,lng,score} at load, no UI code ever touches an index. The
category is an index into POI_CATEGORIES in data/pois-categories.js.

REGIONS

Five files, not six: northern-ireland is merged into ireland, because
data/courses-ireland.js already covers "Republic of Ireland + Northern
Ireland" and the app's nation pills model it the same way. POIs splitting
differently from courses would be a trap for whoever wires the nation filter.

GLOBALS

`window.P_SCOTLAND = [...]`, not the bare `const C_SCOTLAND=[...]` the course
files use. Deliberate: these files are injected lazily at runtime, and a bare
top-level const throws "Identifier has already been declared" if the same
region is injected twice — which a loader will do the moment two legs of one
trip both want Scotland before the first load resolves. Window assignment is
idempotent.

DO NOT add the region files to sw.js's PRECACHE_URLS. Every other data/*.js
is precached, so adding these "for consistency" would pull ~450KB gzipped on
service-worker install and silently undo the lazy loading. Only
data/pois-categories.js (~1KB) belongs there.
"""

import gzip
import importlib.util
import json
import os

HERE = os.path.dirname(os.path.abspath(__file__))
ROOT = os.path.dirname(HERE)
RAW = os.path.join(ROOT, "scripts/output/pois_raw.json")
DATA = os.path.join(ROOT, "data")

# Fetch regions -> shipped file. northern-ireland folds into ireland.
REGION_FILE = {
    "england": "england",
    "scotland": "scotland",
    "wales": "wales",
    "ireland": "ireland",
    "northern-ireland": "ireland",
    "southafrica": "southafrica",
}

# Category -> filter-chip group. Shipped with the labels so that adding a
# category here automatically lands it in a chip, instead of it silently
# vanishing from a hand-maintained map on the UI side.
CATEGORY_GROUP = {
    "Castle": "heritage", "Ruins": "heritage", "Historic site": "heritage",
    "Monument": "heritage", "Cathedral": "heritage", "Church": "heritage",
    "National park": "nature", "Nature reserve": "nature", "Waterfall": "nature",
    "Cave": "nature", "Peak": "nature", "Arch": "nature", "Hot spring": "nature",
    "Viewpoint": "nature", "Gardens": "nature",
    "Beach": "coast", "Lighthouse": "coast",
    "Museum": "culture", "Gallery": "culture", "Artwork": "culture",
    "Zoo": "culture", "Aquarium": "culture", "Attraction": "culture",
    "Distillery": "drink", "Brewery": "drink", "Winery": "drink",
}

BANNER = """/* ============================================================
   data/pois-{name}.js — GOLF-148. Generated by
   scripts/build_poi_data.py; do not hand-edit, regenerate.

   {count} notable POIs. Each entry is
   [name, categoryIndex, lat, lng, score] — categoryIndex indexes
   POI_CATEGORIES in data/pois-categories.js, score is higher-is-better
   and comparable across categories.

   Lazy-loaded at runtime and deliberately NOT in sw.js PRECACHE_URLS.
   ============================================================ */
"""


def load_module(path, name):
    spec = importlib.util.spec_from_file_location(name, path)
    mod = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(mod)
    return mod


def discount_shared_wikidata(pois, base, verbose=True):
    """Stop every piece of a collection inheriting the collection's fame.

    OSM frequently tags each item on an art trail, or each cairn on a ridge,
    with the Wikidata id of the trail or the group rather than one for the item
    itself. The item then scores as though it were the whole collection: one
    47-piece sculpture trail pushed 47 records up the ranking on a single id's
    sitelink count, and 15 separate records named "Cairn" shared one more.

    Records still sharing an id at this point are differently named by
    construction — dedupe merges the same-named ones — so the id cannot be
    describing all of them, and there is no way to tell which one (if any) it
    belongs to. So none of them keeps the count: they fall back to category
    baseline plus tag bonus, which is what an unidentified POI scores anyway.
    """
    by_id = {}
    for p in pois:
        if p.get("wikidata"):
            by_id.setdefault(p["wikidata"], []).append(p)
    shared = {q: v for q, v in by_id.items() if len(v) > 1}

    demoted = 0
    for q, group in shared.items():
        for p in group:
            if not p.get("sitelinks"):
                continue
            p["score"] = base.get(p["category"], 5) + p.get("bonus", 0)
            p["sitelinks"] = 0
            demoted += 1
    if verbose and demoted:
        worst = sorted(shared.items(), key=lambda kv: -len(kv[1]))[:3]
        print(f"  {demoted} records on {len(shared)} shared Wikidata ids lost "
              f"an inherited sitelink count "
              f"(largest: {', '.join(f'{q} x{len(v)}' for q, v in worst)})")
    return pois


def main():
    if not os.path.exists(RAW):
        raise SystemExit(f"{RAW} not found — run fetch_pois.py first")
    pois = json.load(open(RAW, encoding="utf-8"))
    if not pois:
        raise SystemExit("pois_raw.json is empty")

    unscored = [p for p in pois if "score" not in p]
    if unscored:
        raise SystemExit(
            f"{len(unscored)} of {len(pois)} records have no score — the fetch "
            "was interrupted before its Wikidata pass. Re-run fetch_pois.py to "
            "completion, or these POIs ship unranked."
        )

    fp = load_module(os.path.join(HERE, "fetch_pois.py"), "fp")
    dd = load_module(os.path.join(HERE, "dedupe_pois.py"), "dd")
    pois, _ = dd.dedupe(pois, fp.CATEGORY_BASE)
    pois = discount_shared_wikidata(pois, fp.CATEGORY_BASE)

    cats = sorted({p["category"] for p in pois})
    missing = [c for c in cats if c not in CATEGORY_GROUP]
    if missing:
        # Same reasoning as fetch_pois.check_tag_coverage: an unmapped category
        # would ship with no filter chip and simply never appear in the UI.
        raise SystemExit(f"categories with no CATEGORY_GROUP: {missing}")
    index = {c: i for i, c in enumerate(cats)}

    os.makedirs(DATA, exist_ok=True)
    cat_js = ",".join(
        json.dumps({"label": c, "group": CATEGORY_GROUP[c]}, ensure_ascii=False)
        for c in cats
    )
    cat_path = os.path.join(DATA, "pois-categories.js")
    with open(cat_path, "w", encoding="utf-8") as fh:
        fh.write("/* GOLF-148 — generated by scripts/build_poi_data.py. */\n")
        fh.write(f"const POI_CATEGORIES=[{cat_js}];\n")

    buckets = {}
    for p in pois:
        buckets.setdefault(REGION_FILE[p["region"]], []).append(p)

    total_raw = total_gz = 0
    print(f"{len(pois)} POIs, {len(cats)} categories\n")
    for name, rows in sorted(buckets.items()):
        # Highest score first so a consumer that slices the top N without
        # sorting still gets the right answer.
        rows.sort(key=lambda p: (-p["score"], p["name"]))
        body = ",".join(
            json.dumps([p["name"], index[p["category"]], p["lat"], p["lng"], p["score"]],
                       ensure_ascii=False, separators=(",", ":"))
            for p in rows
        )
        js = BANNER.format(name=name, count=len(rows))
        js += f"window.P_{name.upper()}=[{body}];\n"
        path = os.path.join(DATA, f"pois-{name}.js")
        with open(path, "w", encoding="utf-8") as fh:
            fh.write(js)
        b = js.encode()
        gz = len(gzip.compress(b, 9))
        total_raw += len(b)
        total_gz += gz
        print(f"  pois-{name}.js{'':<{max(0, 14 - len(name))}}{len(rows):>6} POIs"
              f"{len(b)/1024:>9.0f}KB{gz/1024:>8.0f}KB gz")
    print(f"  {'TOTAL':<20}{len(pois):>6} POIs{total_raw/1024:>9.0f}KB{total_gz/1024:>8.0f}KB gz")
    print(f"\n  pois-categories.js   {os.path.getsize(cat_path)} bytes "
          f"(this one DOES belong in sw.js PRECACHE_URLS)")


if __name__ == "__main__":
    main()
